#! /bin/bash
mkdir -p presentation_image
convert -verbose -density 600 -quality 100 -resize 1600x -fill white -opaque none "presentation.pdf" "presentation_image/%02d.png"
pip install python-pptx
python - <<END
# Python code
import pptx
import glob
p = pptx.Presentation()
ims = sorted(glob.glob("presentation_image/*"))
blank_slide_layout= p.slide_layouts[6]
for im in ims:
    slide = p.slides.add_slide(blank_slide_layout)
    slide.shapes.add_picture(im, 0, 0, p.slide_width, p.slide_height)
p.save("presentation_image/presentation.pptx")
